"""
Seed Workflow Dataset.

Each workflow is a DAG of tasks. Tasks have:
  task_id          : Unique within the workflow.
  name             : Short human-readable label.
  description      : What the agent must do for this task.
  required_tool    : The tool call that satisfies this task.
  required_params  : Param keys the grader checks for presence.
  dependencies     : task_ids that must be COMPLETED before this task is available.
  business_rule    : Optional plain-English rule the agent must respect.
  rule_check       : "hr_first" | "ticket_exists" | None — grader hook.
  is_blocker       : If True, first tool call always fails (agent must retry/adapt).
  points           : Max reward points for this task (used by grader).

TASK_WORKFLOWS maps difficulty → list of workflow dicts.
The environment cycles through the list for that difficulty.
"""

from __future__ import annotations
from typing import Any, Dict, List

WORKFLOWS: List[Dict[str, Any]] = [

    # ──────────────────────────────────────────────────────────────────
    # EASY  (5–7 tasks, mostly linear, no blockers, 0–1 business rules)
    # ──────────────────────────────────────────────────────────────────
    {
        "workflow_id": "W_E001",
        "task_difficulty": "easy",
        "difficulty_level": 1,
        "name": "Onboard new intern",
        "description": (
            "A new engineering intern is joining next Monday. "
            "Complete the full onboarding: create their HR profile, set up their "
            "Jira account, send a welcome message on Slack, and schedule their "
            "first-day intro meeting."
        ),
        "max_steps": 12,
        "tasks": [
            {
                "task_id": "T1",
                "name": "Create HR profile",
                "description": "Create the intern's HR record with name, role, and department.",
                "required_tool": "hr_create_user",
                "required_params": ["name", "role", "department"],
                "dependencies": [],
                "business_rule": None,
                "rule_check": None,
                "is_blocker": False,
                "points": 1.0,
            },
            {
                "task_id": "T2",
                "name": "Create Jira ticket for setup",
                "description": "Open a Jira task to track the intern's environment setup.",
                "required_tool": "jira_create_ticket",
                "required_params": ["summary", "issue_type"],
                "dependencies": ["T1"],
                "business_rule": "HR profile must exist before creating tool accounts.",
                "rule_check": "hr_first",
                "is_blocker": False,
                "points": 1.0,
            },
            {
                "task_id": "T3",
                "name": "Send welcome Slack message",
                "description": "Post a welcome message to the #general channel mentioning the intern.",
                "required_tool": "slack_send_message",
                "required_params": ["channel", "message"],
                "dependencies": ["T1"],
                "business_rule": None,
                "rule_check": None,
                "is_blocker": False,
                "points": 1.0,
            },
            {
                "task_id": "T4",
                "name": "Schedule intro meeting",
                "description": "Create a 1-hour onboarding meeting with the intern and their manager.",
                "required_tool": "calendar_create_event",
                "required_params": ["title", "attendees"],
                "dependencies": ["T1"],
                "business_rule": None,
                "rule_check": None,
                "is_blocker": False,
                "points": 1.0,
            },
            {
                "task_id": "T5",
                "name": "Send onboarding email",
                "description": "Email the intern with first-day instructions and office details.",
                "required_tool": "email_send",
                "required_params": ["to", "subject", "body"],
                "dependencies": ["T3", "T4"],
                "business_rule": None,
                "rule_check": None,
                "is_blocker": False,
                "points": 1.0,
            },
        ],
    },

    {
        "workflow_id": "W_E002",
        "task_difficulty": "easy",
        "difficulty_level": 1,
        "name": "Report a production bug",
        "description": (
            "A production bug has been reported by a customer. "
            "File a Jira ticket, assign it to the on-call engineer, "
            "notify the team on Slack, and email the affected customer an update."
        ),
        "max_steps": 10,
        "tasks": [
            {
                "task_id": "T1",
                "name": "Create bug ticket",
                "description": "Create a high-priority Bug ticket in Jira describing the issue.",
                "required_tool": "jira_create_ticket",
                "required_params": ["summary", "issue_type", "priority"],
                "dependencies": [],
                "business_rule": None,
                "rule_check": None,
                "is_blocker": False,
                "points": 1.0,
            },
            {
                "task_id": "T2",
                "name": "Assign ticket to on-call engineer",
                "description": "Assign the newly created bug ticket to the on-call engineer.",
                "required_tool": "jira_assign_ticket",
                "required_params": ["ticket_id", "assignee"],
                "dependencies": ["T1"],
                "business_rule": "Ticket must exist before it can be assigned.",
                "rule_check": "ticket_exists",
                "is_blocker": False,
                "points": 1.0,
            },
            {
                "task_id": "T3",
                "name": "Notify team on Slack",
                "description": "Send a message to #incidents with the ticket ID and severity.",
                "required_tool": "slack_send_message",
                "required_params": ["channel", "message"],
                "dependencies": ["T1"],
                "business_rule": None,
                "rule_check": None,
                "is_blocker": False,
                "points": 1.0,
            },
            {
                "task_id": "T4",
                "name": "Email customer acknowledgement",
                "description": "Send the affected customer an email acknowledging the issue.",
                "required_tool": "email_send",
                "required_params": ["to", "subject", "body"],
                "dependencies": ["T2"],
                "business_rule": None,
                "rule_check": None,
                "is_blocker": False,
                "points": 1.0,
            },
        ],
    },

    # ──────────────────────────────────────────────────────────────────
    # MEDIUM  (9–11 tasks, branching DAG, 1 blocker, 2 business rules)
    # ──────────────────────────────────────────────────────────────────
    {
        "workflow_id": "W_M001",
        "task_difficulty": "medium",
        "difficulty_level": 4,
        "name": "Product feature launch",
        "description": (
            "Coordinate the launch of a new product feature. "
            "This requires: project setup in Jira, team channel on Slack, "
            "milestone tickets, stakeholder notifications, a launch calendar event, "
            "and customer-facing release email. Tasks must follow correct order — "
            "notify stakeholders ONLY after milestones are set."
        ),
        "max_steps": 20,
        "tasks": [
            {
                "task_id": "T1",
                "name": "Create launch project in Jira",
                "description": "Create an Epic ticket representing the feature launch.",
                "required_tool": "jira_create_ticket",
                "required_params": ["summary", "issue_type"],
                "dependencies": [],
                "business_rule": None,
                "rule_check": None,
                "is_blocker": False,
                "points": 1.0,
            },
            {
                "task_id": "T2",
                "name": "Create #launch Slack channel",
                "description": "Set up a dedicated Slack channel for the launch team.",
                "required_tool": "slack_create_channel",
                "required_params": ["name"],
                "dependencies": [],
                "business_rule": None,
                "rule_check": None,
                "is_blocker": False,
                "points": 1.0,
            },
            {
                "task_id": "T3",
                "name": "Create design milestone ticket",
                "description": "Create a Story ticket for the design milestone under the Epic.",
                "required_tool": "jira_create_ticket",
                "required_params": ["summary", "issue_type", "project"],
                "dependencies": ["T1"],
                "business_rule": "Milestone tickets must be created under the Epic.",
                "rule_check": "ticket_exists",
                "is_blocker": False,
                "points": 1.0,
            },
            {
                "task_id": "T4",
                "name": "Create engineering milestone ticket",
                "description": "Create a Story ticket for the engineering milestone.",
                "required_tool": "jira_create_ticket",
                "required_params": ["summary", "issue_type"],
                "dependencies": ["T1"],
                "business_rule": None,
                "rule_check": None,
                "is_blocker": False,
                "points": 1.0,
            },
            {
                "task_id": "T5",
                "name": "Assign design milestone",
                "description": "Assign the design milestone ticket to the design lead.",
                "required_tool": "jira_assign_ticket",
                "required_params": ["ticket_id", "assignee"],
                "dependencies": ["T3"],
                "business_rule": None,
                "rule_check": None,
                "is_blocker": False,
                "points": 1.0,
            },
            {
                "task_id": "T6",
                "name": "Assign engineering milestone",
                "description": "Assign the engineering milestone ticket to the tech lead.",
                "required_tool": "jira_assign_ticket",
                "required_params": ["ticket_id", "assignee"],
                "dependencies": ["T4"],
                "business_rule": None,
                "rule_check": None,
                "is_blocker": False,
                "points": 1.0,
            },
            {
                "task_id": "T7",
                "name": "Notify stakeholders on Slack",
                "description": "Post a launch announcement to #general once milestones are assigned.",
                "required_tool": "slack_send_message",
                "required_params": ["channel", "message"],
                "dependencies": ["T5", "T6"],
                "business_rule": "Stakeholders must be notified AFTER milestones are assigned.",
                "rule_check": None,
                "is_blocker": False,
                "points": 1.0,
            },
            {
                "task_id": "T8",
                "name": "Schedule launch review meeting",
                "description": "Create a calendar event for the launch review with all milestone owners.",
                "required_tool": "calendar_create_event",
                "required_params": ["title", "attendees", "date"],
                "dependencies": ["T7"],
                "business_rule": None,
                "rule_check": None,
                "is_blocker": False,
                "points": 1.0,
            },
            {
                "task_id": "T9",
                "name": "Send customer release email",
                "description": "Email the customer segment about the upcoming feature.",
                "required_tool": "email_send",
                "required_params": ["to", "subject", "body"],
                "dependencies": ["T7", "T8"],
                "business_rule": "Customer email must go out AFTER internal review is scheduled.",
                "rule_check": None,
                "is_blocker": True,   # email API returns auth error on first try
                "points": 1.5,
            },
        ],
    },

    # ──────────────────────────────────────────────────────────────────
    # HARD  (13–15 tasks, complex DAG, 2+ blockers, 3+ business rules)
    # ──────────────────────────────────────────────────────────────────
    {
        "workflow_id": "W_H001",
        "task_difficulty": "hard",
        "difficulty_level": 7,
        "name": "Security incident response",
        "description": (
            "A critical security incident has been detected — a potential data breach "
            "affecting enterprise customers. Orchestrate the full incident response: "
            "create and escalate the incident ticket, assemble a war room, notify "
            "affected parties, assign investigators, update the status page, "
            "schedule a postmortem, and send customer communications. "
            "Legal must be notified BEFORE customers. Status page MUST be updated "
            "before any external comms. HR must provision the incident response team."
        ),
        "max_steps": 30,
        "tasks": [
            {
                "task_id": "T1",
                "name": "Create incident ticket (P0)",
                "description": "Open a P0 Bug ticket in Jira for the security incident.",
                "required_tool": "jira_create_ticket",
                "required_params": ["summary", "issue_type", "priority"],
                "dependencies": [],
                "business_rule": None,
                "rule_check": None,
                "is_blocker": False,
                "points": 1.0,
            },
            {
                "task_id": "T2",
                "name": "Create incident response team in HR",
                "description": "Register the incident response team lead in HR.",
                "required_tool": "hr_create_user",
                "required_params": ["name", "role", "department"],
                "dependencies": [],
                "business_rule": None,
                "rule_check": None,
                "is_blocker": False,
                "points": 1.0,
            },
            {
                "task_id": "T3",
                "name": "Create #incident war room channel",
                "description": "Create a private Slack channel for the response team.",
                "required_tool": "slack_create_channel",
                "required_params": ["name", "members"],
                "dependencies": ["T1"],
                "business_rule": "Incident ticket must exist before creating the war room.",
                "rule_check": "ticket_exists",
                "is_blocker": False,
                "points": 1.0,
            },
            {
                "task_id": "T4",
                "name": "Assign incident ticket to team lead",
                "description": "Assign the P0 incident ticket to the response team lead.",
                "required_tool": "jira_assign_ticket",
                "required_params": ["ticket_id", "assignee"],
                "dependencies": ["T1", "T2"],
                "business_rule": "HR record must exist for the assignee.",
                "rule_check": "hr_first",
                "is_blocker": False,
                "points": 1.0,
            },
            {
                "task_id": "T5",
                "name": "Create investigation sub-ticket",
                "description": "Create a sub-task under the P0 ticket for forensic investigation.",
                "required_tool": "jira_create_ticket",
                "required_params": ["summary", "issue_type", "project"],
                "dependencies": ["T1"],
                "business_rule": None,
                "rule_check": None,
                "is_blocker": False,
                "points": 1.0,
            },
            {
                "task_id": "T6",
                "name": "Notify engineering leadership on Slack",
                "description": "Post an urgent message in the war room tagging all leads.",
                "required_tool": "slack_send_message",
                "required_params": ["channel", "message", "mention_user"],
                "dependencies": ["T3", "T4"],
                "business_rule": None,
                "rule_check": None,
                "is_blocker": False,
                "points": 1.0,
            },
            {
                "task_id": "T7",
                "name": "Update incident ticket status",
                "description": "Update the P0 ticket status to 'In Progress'.",
                "required_tool": "jira_update_ticket",
                "required_params": ["ticket_id", "field", "value"],
                "dependencies": ["T4"],
                "business_rule": None,
                "rule_check": None,
                "is_blocker": False,
                "points": 1.0,
            },
            {
                "task_id": "T8",
                "name": "Email legal team",
                "description": "Notify the legal team about the potential breach before any external comms.",
                "required_tool": "email_send",
                "required_params": ["to", "subject", "body"],
                "dependencies": ["T6", "T7"],
                "business_rule": "Legal must be notified BEFORE customers.",
                "rule_check": None,
                "is_blocker": False,
                "points": 1.5,
            },
            {
                "task_id": "T9",
                "name": "Update status page (Jira ticket)",
                "description": "Create a ticket to track the status page update (mandatory before external comms).",
                "required_tool": "jira_create_ticket",
                "required_params": ["summary", "issue_type"],
                "dependencies": ["T7"],
                "business_rule": "Status page must be updated BEFORE customer communications.",
                "rule_check": None,
                "is_blocker": True,  # First API call fails — status page API is down
                "points": 1.5,
            },
            {
                "task_id": "T10",
                "name": "Email affected enterprise customers",
                "description": "Send breach notification email to affected enterprise customers.",
                "required_tool": "email_send",
                "required_params": ["to", "subject", "body"],
                "dependencies": ["T8", "T9"],
                "business_rule": "Status page must be updated and legal notified BEFORE customer email.",
                "rule_check": None,
                "is_blocker": False,
                "points": 2.0,
            },
            {
                "task_id": "T11",
                "name": "Schedule postmortem meeting",
                "description": "Create a calendar event for the postmortem 48 hours after resolution.",
                "required_tool": "calendar_create_event",
                "required_params": ["title", "attendees", "date"],
                "dependencies": ["T6"],
                "business_rule": None,
                "rule_check": None,
                "is_blocker": False,
                "points": 1.0,
            },
            {
                "task_id": "T12",
                "name": "Create postmortem ticket",
                "description": "Open a Jira ticket for the postmortem document and action items.",
                "required_tool": "jira_create_ticket",
                "required_params": ["summary", "issue_type"],
                "dependencies": ["T11"],
                "business_rule": None,
                "rule_check": None,
                "is_blocker": False,
                "points": 1.0,
            },
            {
                "task_id": "T13",
                "name": "Notify all-hands via Slack",
                "description": "Post a company-wide update in #general once customers are notified.",
                "required_tool": "slack_send_message",
                "required_params": ["channel", "message"],
                "dependencies": ["T10"],
                "business_rule": "All-hands notification must come AFTER customer communications.",
                "rule_check": None,
                "is_blocker": False,
                "points": 1.0,
            },
        ],
    },

    # ── EASY #3 ───────────────────────────────────────────────────────────────
    {
        "workflow_id": "W_E003",
        "task_difficulty": "easy",
        "difficulty_level": 1,
        "name": "Offboard departing employee",
        "description": (
            "An employee is leaving the company this Friday. "
            "Complete their offboarding: update their HR status, create a Jira "
            "offboarding ticket, revoke Slack access, schedule a knowledge-transfer "
            "meeting, and send a farewell email to the team."
        ),
        "max_steps": 12,
        "tasks": [
            {
                "task_id": "T1",
                "name": "Update HR status to inactive",
                "description": "Update the employee's HR record status field to 'offboarded'.",
                "required_tool": "hr_update_user",
                "required_params": ["user_id", "field", "value"],
                "dependencies": [],
                "business_rule": None,
                "rule_check": None,
                "is_blocker": False,
                "points": 1.0,
            },
            {
                "task_id": "T2",
                "name": "Create offboarding Jira ticket",
                "description": "Open a Task ticket to track all offboarding checklist items.",
                "required_tool": "jira_create_ticket",
                "required_params": ["summary", "issue_type"],
                "dependencies": ["T1"],
                "business_rule": "HR record must be updated before opening the offboarding ticket.",
                "rule_check": "hr_first",
                "is_blocker": False,
                "points": 1.0,
            },
            {
                "task_id": "T3",
                "name": "Schedule knowledge-transfer meeting",
                "description": "Create a 2-hour handover meeting between the employee and their replacement.",
                "required_tool": "calendar_create_event",
                "required_params": ["title", "attendees", "duration_minutes"],
                "dependencies": ["T1"],
                "business_rule": None,
                "rule_check": None,
                "is_blocker": False,
                "points": 1.0,
            },
            {
                "task_id": "T4",
                "name": "Notify team on Slack",
                "description": "Post a farewell message in #general thanking the employee.",
                "required_tool": "slack_send_message",
                "required_params": ["channel", "message"],
                "dependencies": ["T2"],
                "business_rule": None,
                "rule_check": None,
                "is_blocker": False,
                "points": 1.0,
            },
            {
                "task_id": "T5",
                "name": "Send farewell email",
                "description": "Email the departing employee with a summary of their last-day checklist.",
                "required_tool": "email_send",
                "required_params": ["to", "subject", "body"],
                "dependencies": ["T3", "T4"],
                "business_rule": None,
                "rule_check": None,
                "is_blocker": False,
                "points": 1.0,
            },
        ],
    },

    # ── EASY #4 ───────────────────────────────────────────────────────────────
    {
        "workflow_id": "W_E004",
        "task_difficulty": "easy",
        "difficulty_level": 1,
        "name": "Set up a new project team",
        "description": (
            "A new cross-functional project is kicking off. "
            "Register the project lead in HR, create the project board in Jira, "
            "set up a dedicated Slack channel, and schedule the kick-off meeting."
        ),
        "max_steps": 10,
        "tasks": [
            {
                "task_id": "T1",
                "name": "Register project lead in HR",
                "description": "Create an HR record for the project lead with name, role, and department.",
                "required_tool": "hr_create_user",
                "required_params": ["name", "role", "department"],
                "dependencies": [],
                "business_rule": None,
                "rule_check": None,
                "is_blocker": False,
                "points": 1.0,
            },
            {
                "task_id": "T2",
                "name": "Create project Epic in Jira",
                "description": "Open an Epic ticket representing the new project.",
                "required_tool": "jira_create_ticket",
                "required_params": ["summary", "issue_type"],
                "dependencies": ["T1"],
                "business_rule": "Project lead HR record must exist before creating the project board.",
                "rule_check": "hr_first",
                "is_blocker": False,
                "points": 1.0,
            },
            {
                "task_id": "T3",
                "name": "Create project Slack channel",
                "description": "Create a dedicated Slack channel named after the project.",
                "required_tool": "slack_create_channel",
                "required_params": ["name", "members"],
                "dependencies": ["T1"],
                "business_rule": None,
                "rule_check": None,
                "is_blocker": False,
                "points": 1.0,
            },
            {
                "task_id": "T4",
                "name": "Assign Epic to project lead",
                "description": "Assign the newly created Epic to the project lead.",
                "required_tool": "jira_assign_ticket",
                "required_params": ["ticket_id", "assignee"],
                "dependencies": ["T2"],
                "business_rule": "Epic must exist before assigning.",
                "rule_check": "ticket_exists",
                "is_blocker": False,
                "points": 1.0,
            },
            {
                "task_id": "T5",
                "name": "Schedule kick-off meeting",
                "description": "Create a calendar event for the project kick-off with all stakeholders.",
                "required_tool": "calendar_create_event",
                "required_params": ["title", "attendees", "date"],
                "dependencies": ["T3", "T4"],
                "business_rule": None,
                "rule_check": None,
                "is_blocker": False,
                "points": 1.0,
            },
            {
                "task_id": "T6",
                "name": "Send project kick-off email",
                "description": "Email the full project team with objectives, timeline, and first-meeting details.",
                "required_tool": "email_send",
                "required_params": ["to", "subject", "body"],
                "dependencies": ["T5"],
                "business_rule": None,
                "rule_check": None,
                "is_blocker": False,
                "points": 1.0,
            },
        ],
    },

    # ── MEDIUM #2 ─────────────────────────────────────────────────────────────
    {
        "workflow_id": "W_M002",
        "task_difficulty": "medium",
        "difficulty_level": 4,
        "name": "Customer escalation resolution",
        "description": (
            "A high-value enterprise customer has escalated a critical complaint. "
            "The resolution requires: creating an escalation ticket, assigning a "
            "dedicated account manager, notifying support leadership, scheduling an "
            "emergency call with the customer, drafting an internal RCA ticket, "
            "and sending a formal apology email. "
            "Internal notifications must happen BEFORE contacting the customer. "
            "RCA must be opened before closing the escalation."
        ),
        "max_steps": 22,
        "tasks": [
            {
                "task_id": "T1",
                "name": "Create escalation ticket (P1)",
                "description": "Open a high-priority Bug ticket for the customer escalation.",
                "required_tool": "jira_create_ticket",
                "required_params": ["summary", "issue_type", "priority"],
                "dependencies": [],
                "business_rule": None,
                "rule_check": None,
                "is_blocker": False,
                "points": 1.0,
            },
            {
                "task_id": "T2",
                "name": "Register account manager in HR",
                "description": "Ensure the dedicated account manager has an active HR record.",
                "required_tool": "hr_create_user",
                "required_params": ["name", "role", "department"],
                "dependencies": [],
                "business_rule": None,
                "rule_check": None,
                "is_blocker": False,
                "points": 1.0,
            },
            {
                "task_id": "T3",
                "name": "Assign escalation ticket to account manager",
                "description": "Assign the P1 ticket to the dedicated account manager.",
                "required_tool": "jira_assign_ticket",
                "required_params": ["ticket_id", "assignee"],
                "dependencies": ["T1", "T2"],
                "business_rule": "Account manager HR record must exist before assignment.",
                "rule_check": "hr_first",
                "is_blocker": False,
                "points": 1.0,
            },
            {
                "task_id": "T4",
                "name": "Notify support leadership on Slack",
                "description": "Alert #support-leadership with the escalation ticket ID and customer name.",
                "required_tool": "slack_send_message",
                "required_params": ["channel", "message"],
                "dependencies": ["T3"],
                "business_rule": "Internal teams must be notified BEFORE the customer is contacted.",
                "rule_check": None,
                "is_blocker": False,
                "points": 1.0,
            },
            {
                "task_id": "T5",
                "name": "Open RCA investigation ticket",
                "description": "Create a Story ticket to track the root-cause analysis.",
                "required_tool": "jira_create_ticket",
                "required_params": ["summary", "issue_type"],
                "dependencies": ["T1"],
                "business_rule": None,
                "rule_check": "ticket_exists",
                "is_blocker": False,
                "points": 1.0,
            },
            {
                "task_id": "T6",
                "name": "Schedule emergency call with customer",
                "description": "Create a calendar event for an urgent call with the enterprise customer.",
                "required_tool": "calendar_create_event",
                "required_params": ["title", "attendees", "date"],
                "dependencies": ["T4"],
                "business_rule": "Leadership must be notified before scheduling the customer call.",
                "rule_check": None,
                "is_blocker": False,
                "points": 1.0,
            },
            {
                "task_id": "T7",
                "name": "Update escalation ticket status",
                "description": "Update the P1 ticket status field to 'In Progress'.",
                "required_tool": "jira_update_ticket",
                "required_params": ["ticket_id", "field", "value"],
                "dependencies": ["T3"],
                "business_rule": None,
                "rule_check": None,
                "is_blocker": False,
                "points": 1.0,
            },
            {
                "task_id": "T8",
                "name": "Send formal apology email to customer",
                "description": "Email the enterprise customer with a formal apology and resolution timeline.",
                "required_tool": "email_send",
                "required_params": ["to", "subject", "body"],
                "dependencies": ["T4", "T6", "T7"],
                "business_rule": "Customer email must only be sent after internal alignment and call is scheduled.",
                "rule_check": None,
                "is_blocker": True,
                "points": 1.5,
            },
            {
                "task_id": "T9",
                "name": "Post resolution update to Slack",
                "description": "Update #support-leadership with a summary once the customer has been contacted.",
                "required_tool": "slack_send_message",
                "required_params": ["channel", "message"],
                "dependencies": ["T8"],
                "business_rule": None,
                "rule_check": None,
                "is_blocker": False,
                "points": 1.0,
            },
        ],
    },

    # ── HARD #2 ───────────────────────────────────────────────────────────────
    {
        "workflow_id": "W_H002",
        "task_difficulty": "hard",
        "difficulty_level": 7,
        "name": "Mergers and acquisitions integration",
        "description": (
            "The company has completed an acquisition. Orchestrate the full "
            "integration of the acquired team: register all new employees in HR, "
            "create integration project in Jira with milestone tickets, set up "
            "cross-company Slack channels, notify all stakeholders in the correct "
            "legal order, schedule integration planning meetings, and send "
            "welcome communications. "
            "Legal and executive notifications MUST precede team-wide announcements. "
            "HR records MUST be created before any system access is provisioned. "
            "Integration milestones MUST be assigned before the all-hands is scheduled."
        ),
        "max_steps": 35,
        "tasks": [
            {
                "task_id": "T1",
                "name": "Register acquired CEO in HR",
                "description": "Create an HR record for the acquired company's CEO.",
                "required_tool": "hr_create_user",
                "required_params": ["name", "role", "department"],
                "dependencies": [],
                "business_rule": None,
                "rule_check": None,
                "is_blocker": False,
                "points": 1.0,
            },
            {
                "task_id": "T2",
                "name": "Register acquired CTO in HR",
                "description": "Create an HR record for the acquired company's CTO.",
                "required_tool": "hr_create_user",
                "required_params": ["name", "role", "department"],
                "dependencies": [],
                "business_rule": None,
                "rule_check": None,
                "is_blocker": False,
                "points": 1.0,
            },
            {
                "task_id": "T3",
                "name": "Create M&A integration Epic in Jira",
                "description": "Open an Epic ticket to track the full integration project.",
                "required_tool": "jira_create_ticket",
                "required_params": ["summary", "issue_type"],
                "dependencies": ["T1"],
                "business_rule": "At least one executive HR record must exist before project creation.",
                "rule_check": "hr_first",
                "is_blocker": False,
                "points": 1.0,
            },
            {
                "task_id": "T4",
                "name": "Email legal team for compliance sign-off",
                "description": "Notify legal that integration activities are beginning — mandatory first external step.",
                "required_tool": "email_send",
                "required_params": ["to", "subject", "body"],
                "dependencies": ["T1", "T2"],
                "business_rule": "Legal must be notified before any team-wide communications.",
                "rule_check": None,
                "is_blocker": False,
                "points": 1.5,
            },
            {
                "task_id": "T5",
                "name": "Email executive leadership",
                "description": "Send integration kickoff email to both companies' executive teams.",
                "required_tool": "email_send",
                "required_params": ["to", "subject", "body"],
                "dependencies": ["T4"],
                "business_rule": "Legal sign-off must precede executive comms.",
                "rule_check": None,
                "is_blocker": False,
                "points": 1.5,
            },
            {
                "task_id": "T6",
                "name": "Create HR integration milestone ticket",
                "description": "Create a Story ticket under the Epic for HR system integration.",
                "required_tool": "jira_create_ticket",
                "required_params": ["summary", "issue_type", "project"],
                "dependencies": ["T3"],
                "business_rule": None,
                "rule_check": "ticket_exists",
                "is_blocker": False,
                "points": 1.0,
            },
            {
                "task_id": "T7",
                "name": "Create IT integration milestone ticket",
                "description": "Create a Story ticket under the Epic for IT systems integration.",
                "required_tool": "jira_create_ticket",
                "required_params": ["summary", "issue_type"],
                "dependencies": ["T3"],
                "business_rule": None,
                "rule_check": None,
                "is_blocker": False,
                "points": 1.0,
            },
            {
                "task_id": "T8",
                "name": "Assign HR milestone to HR lead",
                "description": "Assign the HR integration ticket to the HR integration lead.",
                "required_tool": "jira_assign_ticket",
                "required_params": ["ticket_id", "assignee"],
                "dependencies": ["T6"],
                "business_rule": None,
                "rule_check": None,
                "is_blocker": False,
                "points": 1.0,
            },
            {
                "task_id": "T9",
                "name": "Assign IT milestone to IT lead",
                "description": "Assign the IT integration ticket to the IT integration lead.",
                "required_tool": "jira_assign_ticket",
                "required_params": ["ticket_id", "assignee"],
                "dependencies": ["T7"],
                "business_rule": None,
                "rule_check": None,
                "is_blocker": False,
                "points": 1.0,
            },
            {
                "task_id": "T10",
                "name": "Create #integration Slack channel",
                "description": "Set up a cross-company Slack channel for integration coordination.",
                "required_tool": "slack_create_channel",
                "required_params": ["name", "members"],
                "dependencies": ["T5"],
                "business_rule": "Executive communications must go out before team channels are created.",
                "rule_check": None,
                "is_blocker": False,
                "points": 1.0,
            },
            {
                "task_id": "T11",
                "name": "Post integration announcement to Slack",
                "description": "Send the integration announcement to #general with key milestones.",
                "required_tool": "slack_send_message",
                "required_params": ["channel", "message"],
                "dependencies": ["T8", "T9", "T10"],
                "business_rule": "Milestones must be assigned and channel created before team-wide announcement.",
                "rule_check": None,
                "is_blocker": True,
                "points": 1.5,
            },
            {
                "task_id": "T12",
                "name": "Schedule integration planning summit",
                "description": "Create a full-day calendar event for integration planning with both leadership teams.",
                "required_tool": "calendar_create_event",
                "required_params": ["title", "attendees", "date", "duration_minutes"],
                "dependencies": ["T11"],
                "business_rule": None,
                "rule_check": None,
                "is_blocker": False,
                "points": 1.5,
            },
            {
                "task_id": "T13",
                "name": "Create summit prep ticket",
                "description": "Open a Jira task to track summit agenda preparation and pre-reads.",
                "required_tool": "jira_create_ticket",
                "required_params": ["summary", "issue_type"],
                "dependencies": ["T12"],
                "business_rule": None,
                "rule_check": None,
                "is_blocker": False,
                "points": 1.0,
            },
            {
                "task_id": "T14",
                "name": "Send welcome email to all acquired employees",
                "description": "Email the full acquired team with a welcome message and first-week guide.",
                "required_tool": "email_send",
                "required_params": ["to", "subject", "body"],
                "dependencies": ["T11", "T12"],
                "business_rule": "All-team welcome email must come AFTER announcement and summit are confirmed.",
                "rule_check": None,
                "is_blocker": False,
                "points": 2.0,
            },
        ],
    },
]

TASK_WORKFLOWS: Dict[str, List[Dict]] = {
    "easy":   [w for w in WORKFLOWS if w["task_difficulty"] == "easy"],
    "medium": [w for w in WORKFLOWS if w["task_difficulty"] == "medium"],
    "hard":   [w for w in WORKFLOWS if w["task_difficulty"] == "hard"],
}

WORKFLOW_BY_ID: Dict[str, Dict] = {w["workflow_id"]: w for w in WORKFLOWS}
